config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'users/registrations',
             as: :user_registration do
               get :cancel
             end
  end

  namespace :users do
    resource :current_role, only: :update
  end

  namespace :athletes do
    resources :climb_logs, only: [:create, :index]
  end

  resources :gyms, except: :destroy do
    resources :employments, path: 'employees', only: [:index, :create]
  end
  resources :sections, only: [:new, :show] do
    resources :climbs, only: [:new, :create]
    resource :reset, only: [:create]
  end

  resource :profile, only: [:show], controller: :profile
end

app/models/climb.rb
class Climb < ApplicationRecord
  COLORS = {
    '#b71c1c' => 'Red',
    '#ec407a' => 'Pink',
    '#7b1fa2' => 'Purple',
    '#0d47a1' => 'Blue',
    '#00838f' => 'Teal',
    '#2e7d32' => 'Green',
    '#fdd835' => 'Yellow',
    '#ef6c00' => 'Orange',
    '#6d4c41' => 'Brown',
    '#000000' => 'Black',
    '#ffffff' => 'White'
  }.freeze

  validates_presence_of :type
  belongs_to :section
  validates_presence_of :section
  has_one :gym, through: :section
  belongs_to :grade
  before_validation :set_grade_default_if_blank

  # The list of colors is duplicated here in order to ensure that the order used
  # in the enum declaration doesn't change. Once data has been entered in a
  # production environment, special care needs to be taken when adding new
  # options to a Rails enum definition. Either you can only add values to the
  # end of the array, or the production data needs to be migrated.
  enum color: [
    '#b71c1c', '#ec407a', '#7b1fa2', '#0d47a1', '#00838f', '#2e7d32',
    '#fdd835', '#ef6c00', '#6d4c41', '#000000', '#ffffff'
  ]

  def self.active
    where('teardown_date > ? OR teardown_date IS NULL', DateTime.now)
  end

  def self.color_name_for(hex_code)
    COLORS[hex_code].try(:downcase)
  end

  def color_name
    self.class.color_name_for(color)
  end

  # This is the default, however it makes the `Route` and `Boulder` classes use
  # the correct policy class through inheritance.
  def self.policy_class
    ClimbPolicy
  end

  protected

  def set_grade_default_if_blank
    self.grade = Grade.null_object unless grade.present?
  end
end

app/controllers/climbs_controller.rb
class ClimbsController < ApplicationController
  def new
    @climb = Climb.new
    @climb.section_id = params[:section_id]
    authorize @climb
  end

  def create
    @climb = Climb.new(climb_params)
    @climb.section_id = params[:section_id]
    authorize @climb
    if @climb.save
      flash.now[:notice] = 'Climb successfully saved!'
    else
      render :new
    end
  end

  private

  def climb_params
    params.require(:climb).permit(
      :section_id,
      :color,
      :type,
      :grade_id,
      :teardown_date
    )
  end
end

app/helpers/climb_helper.rb
module ClimbHelper
  def data_for_color_options
    Climb.colors.map { |hex, _id| [Climb.color_name_for(hex), hex] }
  end

  def button_to_log_climb(climb, options = {})
    merged_options = {
      class: [climb.color_name, 'climb'],
      remote: true,
      method: :post,
      params: { 'climb_log[climb_id]': climb.id }
    }
    merged_options[:class] += Array(options.delete(:class))
    merged_options = merged_options.merge(options)
    button_to climb.grade.name,
              athletes_climb_logs_path,
              merged_options
  end
end

app/views/climbs/_form.html.haml
= form_for climb, url: section_climbs_path, remote: true do |f|
  %h3 New climb details:
  = render partial: 'shared/error_messages', locals: { target: climb }

  = f.hidden_field :section_id

  %table
    %tr
      %td= f.label :type
      %td
        .climb-type
          = f.label :type, value: 'Boulder' do
            = f.radio_button :type, :Boulder
            %span Boulder

          = f.label :type, value: 'Route' do
            = f.radio_button :type, :Route
            %span Route
    %tr.grade
      %td= f.label :grade
      %td
        = f.select :grade_id, climb.gym.route_grades.pluck(:name, :id), { include_blank: true }, { id: 'route_grades' }
        = f.select :grade_id, climb.gym.boulder_grades.pluck(:name, :id), { include_blank: true }, { id: 'boulder_grades' }
    %tr
      %td= f.label :color
      %td
        = f.select :color, data_for_color_options, { include_blank: true }

  = f.submit 'Save'