config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'users/registrations',
             as: :user_registration do
               get :cancel
             end
  end

  namespace :users do
    resource :current_role, only: :update
  end

  namespace :athletes do
    resources :climb_logs, only: [:create, :index]
  end

  resources :gyms, except: :destroy do
    resources :employments, path: 'employees', only: [:index, :create]
  end
  resources :sections, only: [:new, :show] do
    resources :climbs, only: [:new, :create]
    resource :reset, only: [:create]
  end

  resource :profile, only: [:show], controller: :profile
end

app/models/gym.rb
class Gym < ApplicationRecord
  include ExtractValue
  extract_value_from :name, collections: :sections

  has_many :sections, dependent: :destroy, autosave: true

  belongs_to :route_grade_system, class_name: 'GradeSystem'
  belongs_to :boulder_grade_system, class_name: 'GradeSystem'
  delegate :grades, to: :route_grade_system, prefix: :route
  delegate :grades, to: :boulder_grade_system, prefix: :boulder

  validate :value_cannot_be_blank
  def value_cannot_be_blank
    unless value(reject_blanks: true).present?
      errors.add(:base, 'Cannot create a empty record for a gym. '\
                        'You must define some information for the gym itself, '\
                        'or create some sections for the gym.')
    end
  end

  has_many :memberships
  has_many :athlete_stories, through: :memberships

  def routes
    Climb.where(type: 'Route').where(section_id: section_ids)
  end

  def boulders
    Climb.where(type: 'Boulder').where(section_id: section_ids)
  end

  has_many :employments
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action(only: [:new, :create, :edit, :update]) { authorize Gym }

  def new
    @gym_form ||= GymForm.new
    @gym_form.add_section
  end

  def create
    @gym_form ||= GymForm.new
    @gym_form.attributes = gym_form_params
    if @gym_form.save
      redirect_to gyms_path, notice: 'New gym successfully created!'
    else
      render :new
    end
  end

  def index
    @gyms = Gym.all
  end

  def show
    @gym = Gym.includes(:sections).find(params[:id])
    @route_histogram =
      ClimbHistogram.new(@gym.routes.active, @gym.route_grade_system)
    @boulder_histogram =
      ClimbHistogram.new(@gym.boulders.active, @gym.boulder_grade_system)
  end

  def edit
    @gym_form ||= GymForm.new(Gym.includes(:sections).find(params[:id]))
  end

  def update
    @gym_form = GymForm.new(Gym.includes(:sections).find(params[:id]))
    @gym_form.attributes = gym_form_params
    if @gym_form.save
      gym_name = @gym_form.name || 'Un-named gym'
      redirect_to gyms_path, notice: "#{gym_name} successfully updated!"
    else
      render :edit
    end
  end

  private

  def gym_form_params
    params.require(:gym_form).permit(
      :name,
      :route_grade_system_id,
      :boulder_grade_system_id,
      sections_attributes: [:id, :name, :_destroy]
    )
  end
end

app/views/gyms/_form.html.haml
= form_for gym_form, url: gym_form.url do |f|
  = render partial: 'shared/error_messages', locals: {target: gym_form}

  = f.label :name
  = f.text_field :name

  = f.label :route_grade_system_id, 'Route grade system'
  = f.select :route_grade_system_id, GradeSystem.pluck(:name, :id)

  = f.label :boulder_grade_system_id, 'Boulder grade system'
  = f.select :boulder_grade_system_id, GradeSystem.pluck(:name, :id)

  = field_set_tag 'Sections', id: 'gym_sections' do
    = f.fields_for :sections do |section_form|
      = render partial: 'section_fields', locals: {f: section_form}

    = link_to(new_section_path, id: 'add_new_section', remote: true) do
      = fa_icon 'plus'

  = f.submit 'Save'

app/views/gyms/_section_fields.html.haml
= field_set_tag nil, class: 'section-fields' do
  = f.text_field :name, placeholder: 'name'
  = link_to '#', class: 'remove-section' do
    = fa_icon 'minus'
  = f.hidden_field :_destroy

app/views/gyms/edit.html.haml
%h1
  Editing
  %em= @gym_form.name || 'an un-named climbing gym'
= render_as_local :gym_form

app/views/gyms/index.html.haml
%table#gyms
  %tr
    %th{ colspan: '2' } Gym
  - @gyms.each do |gym|
    %tr
      %td
        = link_to gym.name, gym
      %td
        - if policy(EmployeeList.new(gym)).index?
          = link_to 'Employee List', gym_employments_path(gym)

- if policy(Gym).new?
  = link_to 'Create a New Gym', new_gym_path, id: 'new_gym'

app/views/gyms/new.html.haml
%h1 Create a New Gym
= render_as_local :gym_form

app/views/gyms/show.html.haml
= button_tag class: 'gym-details' do
  %h1= @gym.name

%section.gym-info
  .change-section
    Change Section
    = fa_icon 'angle-double-right', class: 'fa-lg'
  %ul.sections
    - @gym.sections.each do |section|
      %li
        = link_to section.name, section, remote: true
  .histograms
    - if @route_histogram.has_data?
      .route-histogram
        = column_chart @route_histogram.data, xtitle: 'Grade', ytitle: 'Number of Climbs', library: { title: 'Route Breakdown' }
    - if @boulder_histogram.has_data?
      .boulder-histogram
        = column_chart @boulder_histogram.data, xtitle: 'Grade', ytitle: 'Number of Climbs', library: { title: 'Boulder Breakdown' }

- if GymPolicy.new(current_user, Gym).edit?
  = link_to 'Edit Gym Info', edit_gym_path(@gym), class: 'edit-gym-link'