config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'users/registrations',
             as: :user_registration do
               get :cancel
             end
  end

  namespace :users do
    resource :current_role, only: :update
  end

  namespace :athletes do
    resources :climb_logs, only: [:create, :index]
  end

  resources :gyms, except: :destroy do
    resources :employments, path: 'employees', only: [:index, :create]
  end
  resources :sections, only: [:new, :show] do
    resources :climbs, only: [:new, :create]
    resource :reset, only: [:create]
  end

  resource :profile, only: [:show], controller: :profile
end

app/views/layouts/_navbar.html.haml
%nav
  = link_to root_path, class: 'logo' do
    = fa_icon 'line-chart'
    %span#brand_name Climbalytics
  = link_to '#', id: 'navbar_menu_button' do
    = fa_icon 'bars'
    Menu
  #collapsable_content
    %ul#navbar_main_menu
      %li.nav-link
        = link_to 'Gyms', gyms_path
      - if user_signed_in? && (current_user.current_role == 'athlete')
        %li.nav-link
          = link_to 'My Log', athletes_climb_logs_path
    - if user_signed_in?
      %ul#navbar_tools
        %li.nav-link#sign_out
          = link_to 'Sign Out', destroy_user_session_path, method: :delete
        %li.nav-link
          = link_to 'Profile', profile_path
        - if current_user.roles.size > 1
          %li.nav-link#switch_roles
            = link_to 'Switch Roles', '#'
            = form_for current_user, url: users_current_role_path, method: :put do |f|
              = f.collection_select :current_role, current_user.roles, :name, :name

.spacer

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Climbalytics
    %link{ :href => "https://fonts.googleapis.com/css?family=Source+Sans+Pro|Lustria", :rel => "stylesheet", :type => "text/css" }/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "https://www.google.com/jsapi", 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %body
    = render 'layouts/navbar'
    = render_flash
    %main{ class: "#{controller_name} #{action_name}" }
      = yield
    #medium-screen-indicator
    #large-screen-indicator

app/views/layouts/application.js.erb
oldFlashes = $('body > [class*="flash-"]')
oldFlashes.slideUp();
oldFlashes.promise().done( function() {
  oldFlashes.remove();
  $('main').before("<%= j render_flash %>");
});

<%= yield %>